backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "base_de_donnees"
    label: "Base de Données du Site"
    files:
      - label: "👥 Membres"
        name: "membres"
        file: "content/membres.json"
        fields:
          - label: "Liste des membres"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nom Complet", name: "name", widget: "string"}
              - {label: "Rôle", name: "role", widget: "string"}
              - {label: "Photo (Lien http://...)", name: "photo", widget: "markdown", required: false}
      
      - label: "📚 Publications"
        name: "publications"
        file: "content/publications.json"
        fields:
          - label: "Articles"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Auteur", name: "author", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false}
              - {label: "Image (Lien http://...)", name: "image", widget: "string"}
              - {label: "Contenu", name: "content", widget: "markdown"}

      - label: "📅 Événements"
        name: "evenements"
        file: "content/evenements.json"
        fields:
          - label: "Liste des événements"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nom", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false}
              - {label: "Lieu", name: "location", widget: "markdown"}

      - label: "🌍 Actualités"
        name: "actualites"
        file: "content/actualites.json"
        fields:
          - label: "Liste des actualités"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Source", name: "source", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false}
              - {label: "Résumé", name: "summary", widget: "markdown"}
