backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "base_de_donnees"
    label: "Base de Données du Site"
    files:
      - label: "👥 Membres"
        name: "membres"
        file: "content/membres.json"
        fields:
          - label: "Liste des membres"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nom Complet", name: "name", widget: "string", required: false}
              - {label: "Rôle", name: "role", widget: "string", required: false}
              - {label: "Photo (Lien http://...)", name: "photo", widget: "markdown", required: false}
      
      - label: "📚 Publications"
        name: "publications"
        file: "content/publications.json"
        fields:
          - label: "Articles"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string", required: false}
              - {label: "Auteur", name: "author", widget: "string", required: false}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false, required: false}
              - {label: "Image (Lien http://...)", name: "image", widget: "string", required: false}
              - {label: "Contenu", name: "content", widget: "markdown", required: false}

      - label: "📅 Événements"
        name: "evenements"
        file: "content/evenements.json"
        fields:
          - label: "Liste des événements"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nom", name: "title", widget: "string", required: false}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false, required: false}
              - {label: "Lieu", name: "location", widget: "markdown", required: false}

      - label: "🌍 Actualités"
        name: "actualites"
        file: "content/actualites.json"
        fields:
          - label: "Liste des actualités"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string", required: false}
              - {label: "Source (Nom)", name: "source", widget: "string", required: false}
              - {label: "Lien vers l'article officiel (URL)", name: "url", widget: "string", required: false}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false, required: false}
              - {label: "Résumé complet (Markdown)", name: "summary", widget: "markdown", required: false}
